@startuml 工厂方法模式
title 工厂方法模式
left to right direction

' === Pizza ===
abstract class Pizza {
    + {abstract} Prepare(): void
    + {abstract} Bake(): void
    + {abstract} Cut(): void
    + {abstract} Box(): void
}

class CheesePizza extends Pizza {

}
class GreekPizza extends Pizza {

}
class NYCheesePizza extends CheesePizza {

}
class NYGreekPizza extends GreekPizza {

}
class ChicagoCheesePizza extends CheesePizza {

}
class ChicagoGreekPizza extends GreekPizza {

}

' === 商店 ===

abstract class PizzaStore {
    + OrderPizza(type: string): Pizza
    + {abstract} CreatePizza(type: string): Pizza
}

class NYPizzaStore extends PizzaStore {
}

class ChicagoPizzaStore extends PizzaStore {
}


' === 关系 ===
PizzaStore ..> Pizza : creates


@enduml