@startuml 装饰器模式
title 装饰器模式

' ==== 饮料
abstract class Beverage {
    + {abstract} GetDescription(): string
    + {abstract} Cost(): decimal
}

class HouseBlend extends Beverage {}

class DarkRoast extends Beverage {}

' ==== 调料
abstract class Seasoning extends Beverage {
    - beverage: Beverage
    + Seasoning(beverage: Beverage)
}

class SteamedMilk extends Seasoning {}
class Mocha extends Seasoning {}
class Soy extends Seasoning {}
class Whip extends Seasoning {}

' === 容量
abstract class Size extends Beverage {
    - beverage: Beverage
    + Size(beverage: Beverage)
}
class Venti extends Size {}
class Grande extends Size {}
class Tall extends Size {}


' ==== 关系
Seasoning --o Beverage

@enduml