@startuml 装饰器模式
title 装饰器模式

' ==== 饮料
abstract class Beverage {
    + Seasonings: List<seasoning>
    + GetDescription(): string
    + {abstract} GetSeasoningsDescription(): string
    + Cost(): decimal
    + {abstract} GetSeasoningsCost(): decimal
    + AddSeasoning(): void
}

class HouseBlend extends Beverage {}

class DarkRoast extends Beverage {}

' ==== 调料
abstract class Seasoning {
    + {abstract} GetDescription(): string
    + {abstract} Cost(): decimal
}

class SteamedMilk extends Seasoning {}
class Mocha extends Seasoning {}
class Soy extends Seasoning {}
class Whip extends Seasoning {}

' ==== 关系
Beverage --> Seasoning : "被装饰"

@enduml