@startuml 观察者模式
title 观察者模式

interface ISubject {
    + Register(observer: IObserver): void
    + Remove(observer: IObserver): void
    + Notify(): void
}

class WeatherData implements ISubject {
    - Observers: List<IObserver>

    + GetTemperature(): float
    + GetHumidity(): float
    + GetPressure(): float

    + MeasurementsChanged(): void
}

interface IObserver {
    + Update(): void
}

class CurrentConditionsDisplay implements IObserver {
    + Subject: ISubject
    + Update(): void
}

class StatisticsDisplay implements IObserver {
    + Subject: ISubject
    + Update(): void
}

class ForecastDisplay implements IObserver {
    + Subject: ISubject
    + Update(): void
}

class HeatIndexDisplay implements IObserver {
    + Subject: ISubject
    + Update(): void
}

ISubject "1" ..> "*" IObserver : 注册

@enduml